// header
#include<fstream>
#include<conio.h>
#include<stdlib.h>
#include<stdio.h>
#include<string.h>
#include<iomanip>
#include<dos.h>
#include<iostream>
using namespace std;

void menu();
#include"C:\Users\skori\C++ Training\Store-Management-System\PASSWORD.CPP"
#include"C:\Users\skori\C++ Training\Store-Management-System\NUMBER.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\CLASS.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\ADD.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\SHOW.CPP"
#include"C:\Users\skori\C++ Training\Store-Management-System\DELETE.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\MODIFY.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\REORDER.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\BILL.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\PURCHASE.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\ADMIN.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\CUSTOMER.CPP"
#include "C:\Users\skori\C++ Training\Store-Management-System\MENU.CPP"



